PRONOMS = {
    'em' : ['em', "m'", '-me', "'m"],
    'et' : ['et', "t'", '-te', "'t"],
    'es' : ['es', "s'", '-se', "'s"],
    'en' : ['en', "n'", '-ne', "'n"],
    'el' : ['el', "l'", '-el', "'l"],
    'la' : ['la', "l'", '-la', "-la"], #paraula femenina primera sil·laba àtona (h, hi, u, hu)
    'ens' : ['ens', "ens", '-nos', "'ns"],
    'us' : ['us', "us", '-vos', "-us"],
    'els' : ['els', "els", '-los', "'ls"],
    'les' : ['les', "les", '-les', "-les"],
    'li' : ['li', "li", '-li', "-li"],
    'ho' : ['ho', "ho", '-ho', "-ho"],
    'hi' : ['hi', "hi", '-hi', "-hi"]
}

VERBS_CP = ["FER", "DIR", "ELEGIR", "NOMENAR"]

m = ["es", "et", "us", "em", "ens", "li", "els (ci)", "el", "els (cd)", "la", "les", "en"]
n = ["hi", "en", "ho", "les", "la", "els (cd)", "el", "els (ci)", "li", "ens", "em", "us", "et"]

PRON_BINARIES = [[[["s'hi"], ["-s'hi"]], [["se'n", "se n'"], ["-se'n"]], [["s'ho"], ["-s'ho"]], [["se les"], ["-se-les"]], [["se la", "se l'"], ["-se-la"]], [["se'ls"], ["-se'ls"]], [["se'ls"], ["-se'ls"]], [["se'ls"], ["-se'ls"]], [["se li"], ["-se-li"]], [["se'ns"], ["-se'ns"]], [["se'm", "se m'"], ["-se'm"]], [["se us"], ["-se-us"]], [["se't", "se t'"], ["-se't"]]], 
[[["t'hi"], ["-t'hi"]], [["te'n", "te n'"], ["te'n"]], [["t'ho"], ["-t'ho"]], [["te les"], ["-te-les"]], [["te la", "te l'"], ["-te-la"]], [["te'ls"], ["-te'ls"]], [["te'l", "te l'"], ["-te'l"]], [["te'ls"], ["-te'ls"]], [["te li"], ["-te-li"]], [["te'ns"], ["-te'ns"]], [["te'm", "te m'"], ["-te'm"]]], 
[[["us hi"], ["-vos-hi", "-us-hi"]], [["us en", "us n'"], ["-vos-en", "-us-en"]], [["us ho"], ["-vos-ho", "-us-ho"]], [["us les"], ["-vos-les", "-us-les"]], [["us la", "us l'"], ["-vos-la", "-us-la"]], [["us els"], ["vos-els", "-us-els"]], [["us el", "us l'"], ["-vos-el", "-us-el"]], [["us els"], ["-vos-els", "-us-els"]], [["us li"], ["-vos-li", "-us-li"]], [["us ens"], ["-vos-ens", "-us-ens"]], [["us em", "us m'"], ["-vos-em", "-us-em"]]], 
[[["m'hi"], ["-m'hi"]], [["me'n", "me n'"], ["-me'n"]], [["m'ho"], ["-m'ho"]], [["me les"], ["me-les"]], [["me la", "me l'"], ["-me-la"]], [["me'ls"], ["-me'ls"]], [["me'l", "me l'"], ["-me'l"]], [["me'ls"], ["-me'ls"]], [["me li"], ["me-li"]]], 
[[["ens hi"], ["-nos hi", "'ns-hi"]], [["ens en", "ens n'"], ["-nos-en", "'ns-en"]], [["ens ho"], ["-nos-ho", "'ns-ho"]], [["ens les"], ["-nos-les", "'ns-les"]], [["ens la", "ens l'"], ["-nos-la", "'ns-la"]], [["ens els"], ["-nos-els", "'ns-els"]], [["ens el", "ens l'"], ["-nos-el", "'ns-el"]], [["ens els"], ["-nos-els", "'ns-els"]], [["ens li"], ["-nos-li", "'ns-li"]]], 
[[["li hi"], ["-li-hi"]], [["li'n", "li n'"], ["-li'n"]], [["li ho"], ["-li-ho"]], [["les hi"], ["-les-hi"]], [["la hi"], ["-la-hi"]], [["els hi"], ["-los-hi", "'ls-hi"]], [["l'hi"], ["-l'hi"]]], 
[[["els hi"], ["-los hi", "'ls-hi"]], [["els en", "els n'"], ["-los-en", "'ls-en"]], [["els ho"], ["-los-ho", "'ls-ho"]], [["els les"], ["-los-les", "'ls-les"]], [["els la", "els l'"], ["-los-la", "'ls-la"]], [["els els"], ["-los-els", "'ls-els"]], [["els el", "els l'"], ["-los-el", "'ls-el"]]], 
[[["l'hi"], ["-l'hi"]], [["l'en", "el n'"], ["-l'en"]]], 
[[["els hi"], ["-los-hi", "'ls-hi"]], [["els en", "els n'"], ["-los-en", "'ls-en"]]], 
[[["la hi"], ["-la-hi"]], [["la'n", "la n'"], ["-la'n"]]], 
[[["les hi"], ["-les-hi"]], [["les en", "les n'"], ["-les-en"]]], 
[[["n'hi"], ["-n'hi"]]]]

VERBS_CONJUGATS = {'SEMBLAR': ['semblo', 'sembles', 'sembla', 'semblem', 'sembleu', 'semblen', 'he semblat', 'has semblat', 'ha semblat', 'hem semblat', 'heu semblat', 'han semblat', 'semblava', 'semblaves', 'semblava', 'semblàvem', 'semblàveu', 'semblaven', 'havia semblat', 'havies semblat', 'havia semblat', 'havíem semblat', 'havíeu semblat', 'havien semblat', 'semblí', 'semblares', 'semblà', 'semblàrem', 'semblàreu', 'semblaren', 'haguí semblat', 'hagueres semblat', 'hagué semblat', 'haguérem semblat', 'haguéreu semblat', 'hagueren semblat', 'vaig semblar', 'vas semblar', 'va semblar', 'vam semblar', 'vau semblar', 'van semblar', 'vaig haver semblat', 'vas haver semblat', 'va haver semblat', 'vam haver semblat', 'vau haver semblat', 'van haver semblat', 'semblaré', 'semblaràs', 'semblarà', 'semblarem', 'semblareu', 'semblaran', 'hauré semblat', 'hauràs semblat', 'haurà semblat', 'haurem semblat', 'haureu semblat', 'hauran semblat', 'semblaria', 'semblaries', 'semblaria', 'semblaríem', 'semblaríeu', 'semblarien', 'hauria semblat', 'hauries semblat', 'hauria semblat', 'hauríem semblat', 'hauríeu semblat', 'haurien semblat', 'haguera semblat', 'hagueres semblat', 'haguera semblat', 'haguérem semblat', 'haguéreu semblat', 'hagueren semblat', 'sembli', 'semblis', 'sembli', 'semblem', 'sembleu', 'semblin', 'semblés', 'semblessis', 'semblés', 'sembléssim', 'sembléssiu', 'semblessin', 'hagi semblat', 'hagis semblat', 'hagi semblat', 'hàgim semblat', 'hàgiu semblat', 'hagin semblat', 'hagués semblat', 'haguessis semblat', 'hagués semblat', 'haguéssim semblat', 'haguéssiu semblat', 'haguessin semblat', 'sembla', 'sembli', 'semblem', 'sembleu', 'semblin'], 
    "ELEGIR" : ['elegeixo', 'elegeixes', 'elegeix', 'elegim', 'elegiu', 'elegeixen', 'he elegit', 'has elegit', 'ha elegit', 'hem elegit', 'heu elegit', 'han elegit', 'elegia', 'elegies', 'elegia', 'elegíem', 'elegíeu', 'elegien', 'havia elegit', 'havies elegit', 'havia elegit', 'havíem elegit', 'havíeu elegit', 'havien elegit', 'elegí', 'elegires', 'elegí', 'elegírem', 'elegíreu', 'elegiren', 'haguí elegit', 'hagueres elegit', 'hagué elegit', 'haguérem elegit', 'haguéreu elegit', 'hagueren elegit', 'vaig elegir', 'vas elegir', 'va elegir', 'vam elegir', 'vau elegir', 'van elegir', 'vaig haver elegit', 'vas haver elegit', 'va haver elegit', 'vam haver elegit', 'vau haver elegit', 'van haver elegit', 'elegiré', 'elegiràs', 'elegirà', 'elegirem', 'elegireu', 'elegiran', 'hauré elegit', 'hauràs elegit', 'haurà elegit', 'haurem elegit', 'haureu elegit', 'hauran elegit', 'elegiria', 'elegiries', 'elegiria', 'elegiríem', 'elegiríeu', 'elegirien', 'hauria elegit', 'hauries elegit', 'hauria elegit', 'hauríem elegit', 'hauríeu elegit', 'haurien elegit', 'haguera elegit', 'hagueres elegit', 'haguera elegit', 'haguérem elegit', 'haguéreu elegit', 'hagueren elegit', 'elegeixi', 'elegeixis', 'elegeixi', 'elegim', 'elegiu', 'elegeixin', 'elegís', 'elegissis', 'elegís', 'elegíssim', 'elegíssiu', 'elegissin', 'hagi elegit', 'hagis elegit', 'hagi elegit', 'hàgim elegit', 'hàgiu elegit', 'hagin elegit', 'hagués elegit', 'haguessis elegit', 'hagués elegit', 'haguéssim elegit', 'haguéssiu elegit', 'haguessin elegit', 'elegeix', 'elegeixi', 'elegim', 'elegiu', 'elegeixin'],
    "DIR": ['dic', 'dius', 'diu', 'diem', 'dieu', 'diuen', 'he dit', 'has dit', 'ha dit', 'hem dit', 'heu dit', 'han dit', 'deia', 'deias', 'deia', 'dèiem', 'dèieu', 'deien', 'havia dit', 'havies dit', 'havia dit', 'havíem dit', 'havíeu dit', 'havien dit', 'diguí', 'digueres', 'digué', 'diguérem', 'diguéreu', 'digueren', 'haguí dit', 'hagueres dit', 'hagué dit', 'haguérem dit', 'haguéreu dit', 'hagueren dit', 'vaig dir', 'vas dir', 'va dir', 'vam dir', 'vau dir', 'van dir', 'vaig haver dit', 'vas haver dit', 'va haver dit', 'vam haver dit', 'vau haver dit', 'van haver dit', 'diré', 'diràs', 'dirà', 'direm', 'direu', 'diran', 'hauré dit', 'hauràs dit', 'haurà dit', 'haurem dit', 'haureu dit', 'hauran dit', 'diria', 'diries', 'diria', 'diríem', 'diríeu', 'dirien', 'hauria dit', 'hauries dit', 'hauria dit', 'hauríem dit', 'hauríeu dit', 'haurien dit', 'haguera dit', 'hagueres dit', 'haguera dit', 'haguérem dit', 'haguéreu dit', 'hagueren dit', 'digui', 'diguis', 'digui', 'diguem', 'digueu', 'diguin', 'digués', 'diguessis', 'digués', 'diguéssim', 'diguéssiu', 'diguessin', 'hagi dit', 'hagis dit', 'hagi dit', 'hàgim dit', 'hàgiu dit', 'hagin dit', 'hagués dit', 'haguessis dit', 'hagués dit', 'haguéssim dit', 'haguéssiu dit', 'haguessin dit', 'digues', 'digui', 'diguem', 'digueu', 'diguin', 'dir', 'haver dit', 'dient', 'havent dit', 'dit', 'dita', 'dits', 'dites'],
    "FER": ['faig', 'fas', 'fa', 'fem', 'feu', 'fan', 'he fet', 'has fet', 'ha fet', 'hem fet', 'heu fet', 'han fet', 'feia', 'feies', 'feia', 'fèiem', 'fèieu', 'feien', 'havia fet', 'havies fet', 'havia fet', 'havíem fet', 'havíeu fet', 'havien fet', 'fiu', 'feres', 'féu', 'férem', 'féreu', 'feren', 'haguí fet', 'hagueres fet', 'hagué fet', 'haguérem fet', 'haguéreu fet', 'hagueren fet', 'vaig fer', 'vas fer', 'va fer', 'vam fer', 'vau fer', 'van fer', 'vaig haver fet', 'vas haver fet', 'va haver fet', 'vam haver fet', 'vau haver fet', 'van haver fet', 'faré', 'faràs', 'farà', 'farem', 'fareu', 'faran', 'hauré fet', 'hauràs fet', 'haurà fet', 'haurem fet', 'haureu fet', 'hauran fet', 'faria', 'faries', 'faria', 'faríem', 'faríeu', 'farien', 'hauria fet', 'hauries fet', 'hauria fet', 'hauríem fet', 'hauríeu fet', 'haurien fet', 'haguera fet', 'hagueres fet', 'haguera fet', 'haguérem fet', 'haguéreu fet', 'hagueren fet', 'faci', 'facis', 'faci', 'fem', 'feu', 'facin', 'fes', 'fessis', 'fes', 'féssim', 'féssiu', 'fessin', 'hagi fet', 'hagis fet', 'hagi fet', 'hàgim fet', 'hàgiu fet', 'hagin fet', 'hagués fet', 'haguessis fet', 'hagués fet', 'haguéssim fet', 'haguéssiu fet', 'haguessin fet', 'fes', 'faci', 'fem/ facem', 'feu', 'facin'],
    "NOMENAR": ['nomeno', 'nomene', 'nomèn', 'nomenes', 'nomena', 'nomenem', 'nomenam', 'nomene', 'nomenau', 'nomenen', 'he nomenat', 'has nomenat', 'ha nomenat', 'hem nomenat', 'heu nomenat', 'han nomenat', 'nomenava', 'nomenaves', 'nomenava', 'nomenàvem', 'nomenàveu', 'nomenaven', 'havia nomenat', 'havies nomenat', 'havia nomenat', 'havíem nomenat', 'havíeu nomenat', 'havien nomenat', 'nomení', 'nomenares', 'nomenà', 'nomenàrem', 'vós nomenàreu', 'nomenaren', 'vaig nomenar', 'vas nomenar', 'vares nomenar', 'va nomenar', 'vam nomenar', 'vàrem nomenar', 'vau nomenar', 'van nomenar', 'haguí nomenat', 'hagueres nomenat', 'hagué nomenat', 'haguérem nomenat', 'haguéreu nomenat', 'hagueren nomenat', 'vaig haver nomenat', 'vas haver nomenat', 'va haver nomenat', 'vam haver nomenat', 'vau haver nomenat', 'van haver nomenat', 'nomenaré', 'nomenaràs', 'nomenarà', 'nomenarem', 'nomenareu', 'nomenaran', 'hauré nomenat', 'hauràs nomenat', 'haurà nomenat', 'haurem nomenat', 'haureu nomenat', 'hauran nomenat', 'nomenaria', 'nomenaries', 'nomenaria', 'nomenaríem', 'nomenaríeu', 'nomenarien', 'hauria nomenat', 'hauries nomenat', 'hauria nomenat', 'hauríem nomenat', 'hauríeu nomenat', 'haurien nomenat']
}